apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: nfs-1.goern.example.com
    path: /srv/nfs/vol003
